/** Region code to English display name. Used when locale is EN. */
export const REGION_NAMES_EN: Record<string, string> = {
  US: "United States",
  GB: "United Kingdom",
  CA: "Canada",
  SG: "Singapore",
  AU: "Australia",
  DE: "Germany",
  FR: "France",
  ID: "Indonesia",
  JP: "Japan",
  IN: "India",
  BR: "Brazil",
  MX: "Mexico",
  HU: "Hungary",
  RO: "Romania",
  PO: "Portugal",
  SO: "South Africa",
  NI: "Nigeria",
  PU: "Puerto Rico",
  CH: "China",
  other: "Other",
};
